### ISSUE TITLE
3.0.0 Beta Released!

### ISSUE THREAD

**Issue by rgomezp** [OneSignal/react-onesignal#101]
🚧 Beta release. Please test thoroughly prior to production use. 🚧

In this major version beta release for the OneSignal SDK, we are making a significant shift from a device-centered model to a user-centered model. A user-centered model allows for more powerful omni-channel integrations within the OneSignal platform.

For information please see the [migration guide](https://github.com/OneSignal/react-onesignal/blob/3.0.0/MigrationGuide.md)

We are seeking feedback! Please leave questions and comments in the thread below.

**Comment by jkasten2** [comment]
3.0.0 is now out of beta and has been released! See the full release notes:
https://github.com/OneSignal/react-onesignal/releases/tag/3.0.0

This means no breaking changes will be made in 3.0.0. If you find a bug or have a feature require please create a new issue.
