### ISSUE TITLE
[question]: isPushNotificationsSupported not in interface?

### ISSUE THREAD

**Issue by obbila** [OneSignal/react-onesignal#113]
### How can we help?

How should I check if OneSignal is supported?

It does not appear to be in the interface and this is the error you get if you try:

OneSignal.isPushNotificationsSupported()

```
react_onesignal__WEBPACK_IMPORTED_MODULE_0__.default.isPushNotificationsSupported is not a function

```

**Comment by rgomezp** [comment]
The function `isPushSupported` is available on https://github.com/OneSignal/react-onesignal/issues/101. Please upgrade to use it. 

Enjoy!
