### ISSUE TITLE
Uncaught (in promise) TypeError: Type error

### ISSUE THREAD

**Issue by tcetin** [OneSignal/react-onesignal#114]
### How can we help?

I am getting `Uncaught (in promise) TypeError: Type error;` when try to initialize the OneSignalSDK. 

Here is my implementation

```
		OneSignal.init({
			appId,
			serviceWorkerPath: "OneSignalSDKWorker.js",
			allowLocalhostAsSecureOrigin: true,
			safari_web_id: process.env.NEXT_PUBLIC_SAFARI_WEB_ID
		}).then(() => {
			OneSignal.registerForPushNotifications()
		})
```

How can I solve this problem?

**Comment by DavidQuartz** [comment]
So you still have this problem? Can you provide more context as to what environment you are working in and perhaps a more descriptive error log from a catch block?

**Comment by jkasten2** [comment]
@tcetin We will need more information to investigate. I recommend trying the new [3.0.0](https://github.com/OneSignal/react-onesignal/releases/tag/3.0.0) version as this may have been fixed there. If not, please open a new issue with more details on your error.
