### ISSUE TITLE
[Bug]: Request to Include `isOptedOut` method

### ISSUE THREAD

**Issue by DavidQuartz** [OneSignal/react-onesignal#115]
### What's on your mind?

I'm using your react-onesignal library in a project for handling push notifications. I noticed that currently there doesn't seem to be a method to check whether a user has opted out of notifications. I've found isOptedOut available in the OneSignal web SDK, but it appears this function is not currently included in the react-onesignal package.

Having the ability to check if users have opted out of notifications directly through react-onesignal would be beneficial for managing user preferences within our application.

Here's a sample use case scenario:
```javascript
import OneSignal from 'react-onesignal';

OneSignal.isOptedOut().then(isOptedOut => {
    if (isOptedOut) {
        console.log('User has opted out of notifications');
    } else {
        console.log('User has not opted out of notifications');
    }
});
```

Could you consider adding this functionality in a future update? I believe this would make react-onesignal more flexible and complete for managing user notification preferences.

**Comment by rgomezp** [comment]
Howdy, 
We will no longer be making large investments (e.g API changes) to the 2.0 SDK. 

However, we have the functionality you're looking for in the latest 3.0 [major release](https://github.com/OneSignal/react-onesignal/blob/user-model/v1/MigrationGuide.md#push-subscription-namespace) (beta).

We encourage you to migrate to v3 if possible.

Enjoy!
