### ISSUE TITLE
[Bug]: identifyUser: malformed request

### ISSUE THREAD

**Issue by KDederichs** [OneSignal/react-onesignal#121]
### What happened?

```
app-index.js:31 Login: Error while identifying/upserting user: identifyUser: malformed request: {"errors":[{"code":"auth-1","title":"This operation requires 'Authorization' in the HTTP header"}]}
```

While calling `OneSignal.login` on the new V3 version

### What browsers are you seeing the problem on?

Chrome (Chromium)

### What operating system are you running?

13.4

### Steps to reproduce?

```Markdown
Call OneSignal.login
```

### What did you expect to happen?

No error

**Comment by jkasten2** [comment]
@KDederichs Thanks for reaching out!

It sounds like you have [OneSignal Identity Verification](https://documentation.onesignal.com/docs/identity-verification) enabled on your OneSignal app. This isn't support by the SDK yet but is coming soon.

**Comment by arianshirepublik** [comment]
> @KDederichs Thanks for reaching out!
> 
> It sounds like you have [OneSignal Identity Verification](https://documentation.onesignal.com/docs/identity-verification) enabled on your OneSignal app. This isn't support by the SDK yet but is coming soon.

@jkasten2  when will it support ?

**Comment by websitevirtuoso** [comment]
how to disable it? it can't migrate my code to latest version

**Comment by jinliu9508** [comment]
To disable it, you may navigate to OneSignal dashboard -> Settings -> Key & IDs -> Identity Verification -> turn Token Identity Verification off.
