### ISSUE TITLE
[Question]: How to mute notification when user on a specific page?

### ISSUE THREAD

**Issue by asaadbaw** [OneSignal/react-onesignal#123]
### How can we help?

Hello,

I am currently using React.js to build a chat page, and I am looking to implement a feature that mutes notifications when the user is actively engaged in the chat. I'm seeking functionality akin to the following:

OneSignal.inFocusDisplaying();

**Comment by sergio-dd** [comment]
Hellow, any update, I have the same problem, I also have a chat system.

**Comment by jennantilla** [comment]
Hello there! Apologies for the delay in response. In our latest SDK major version, we have the [foregroundWillDisplay](https://documentation.onesignal.com/docs/web-sdk-reference#foregroundwilldisplay) method which sounds like it may work for your use case. Please see our [migration guide](https://github.com/OneSignal/react-onesignal/blob/main/MigrationGuide.md) for information on upgrading. Thanks!
