### ISSUE TITLE
[Bug]: Login: No identity model found

### ISSUE THREAD

**Issue by arianshirepublik** [OneSignal/react-onesignal#126]
### What happened?

 "react-onesignal": "^3.0.1",

When I am using  import OneSignal from 'react-onesignal'

OneSignal.login(id, token.oneSignalUserIdToken)

new user login show error:

LoginManager.js:95 n: Login: No identity model found
    at Cn.<anonymous> (https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.es6.js?v=160002:1:262495)
    at Generator.next (<anonymous>)
    at r (https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.es6.js?v=160002:1:325606)

<img width="954" alt="image" src="https://github.com/OneSignal/react-onesignal/assets/133647949/09521623-ff7c-4bbf-b943-961be22f3e7b">

### What browsers are you seeing the problem on?

Chrome (Chromium)

### What operating system are you running?

macOS Ventura 13.0

### Steps to reproduce?

```Markdown
OneSignal.login(id, token.oneSignalUserIdToken)

new user login show error:

LoginManager.js:95 n: Login: No identity model found
    at Cn.<anonymous> (https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.es6.js?v=160002:1:262495)
    at Generator.next (<anonymous>)
    at r (https://cdn.onesignal.com/sdks/web/v16/OneSignalSDK.page.es6.js?v=160002:1:325606)
```

### What did you expect to happen?

we can log in correctly and then perform personalized push

**Comment by emiltsang-flow** [comment]
@arianshirepublik How did you fix the issue?

**Comment by arianshirepublik** [comment]
> @arianshirepublik How did you fix the issue?

Hi @emiltsang-flow 

The V3 version has user identification problems will occur. Use the V2 version. `"react-onesignal": "2.0.3",`

https://github.com/OneSignal/react-onesignal/blob/user-model/v1/MigrationGuide.md

**Comment by emiltsang-flow** [comment]
Thanks @arianshirepublik ,
lets see whether i can find the corresponding release in the `vue` version.
