### ISSUE TITLE
[Bug]: The OneSignal web SDK can only be initialized once. Extra initializations are ignored. Please remove calls initializing the SDK more than once.

### ISSUE THREAD

**Issue by SneakingSlayer** [OneSignal/react-onesignal#129]
### What happened?

The package seems to be  throwing this new error:

`OneSignal: The OneSignal web SDK can only be initialized once. Extra initializations are ignored. Please remove calls initializing the SDK more than once.`

Regardless of how you initialize OneSignal.

Code below:

```
const [isInitializedOneSignal, setIsInitializedOneSignal] = useState(false);

 const initOneSignal = useCallback(async () => {
     // If OneSignal is already initialized then return
     if (isInitializedOneSignal) {
      return;
    }

    // Initialize OneSignal
    await OneSignal.init({ 
      appId: 'MY-APP-ID', 
      allowLocalhostAsSecureOrigin: true
    });

    setIsInitializedOneSignal(true);

    // Open subscribe prompt
    OneSignal.Slidedown.promptPush();
  }, [isInitializedOneSignal]);
```

```
  // Initialize One Signal
  useEffect(() => {
    void initOneSignal();
  },[initOneSignal]);

```
### What browsers are you seeing the problem on?

Firefox, Chrome (Chromium), Safari, Microsoft Edge, Opera, Brave

### What operating system are you running?

asdasasdasasdasasdasasdas

### Steps to reproduce?

```Markdown
1. Initialize OneSignal
2. Run the app
```

### What did you expect to happen?

Should not throw any errors

**Comment by SneakingSlayer** [comment]
Just realized React's StrictMode renders everything twice hence this error.

**Comment by sherwinski** [comment]
Hey @damianobarbati,

Unfortunately, there isn't a designated property that tells you if the web SDK is already initialized. I would recommend doing what @SneakingSlayer did in their original example and keep track of it through some kind of state variable.
