### ISSUE TITLE
Uncaught (in promise) Error: OneSignal is not setup correctly

### ISSUE THREAD

**Issue by thearchibold** [OneSignal/react-onesignal#20]
`import ReactOneSignal from 'react-onesignal';`
`const options = {
    safari_web_id:"web.xxxxx-xxxxxx",
    allowLocalhostAsSecureOrigin: true,
    notifyButton:{
        enable:true,
    }
};`
`ReactOneSignal.initialize("xxxx-xxxxx-xxxxx-xx", options);`

calling

`ReactOneSignal.getPlayerId(function(userId) {
                    console.log('user id', userId);
                });`
results in the error above.

Am I missing anything in the initialization?

**Comment by pedro-lb** [comment]
Hey there @thearchibold !

It's possible that OneSignal hasn't initialized yet, so you're getting this error because you're trying to configure it before it was completely initialized.

Have you tried using our hook to handle OneSignal configuration?

Here's an example:

```jsx
import OneSignal, { useOneSignalSetup } from 'react-onesignal';

type AppProps = {
  user: {
    id: string;
    email: string;
  };
};

function App(props: AppProps) {
  const { user } = props;

  useOneSignalSetup(() => {
    OneSignal.setEmail(user.email);
    OneSignal.setExternalUserId(user.id);
  });
}
```

**Comment by thearchibold** [comment]
Oh ok thanks @pedro-lb , I'd try that and revert

**Comment by pedro-lb** [comment]
Let me know what happens! 😄

**Comment by djaffer** [comment]
Can you provide an example how to use this hook in js not ts? I tried to call this and kept getting error for hook cannot be used in ×
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
▶ 2 stack frames were collapsed.

A better solution could be you promisify this and return OneSignal.initialize once it is ready.


```
import OneSignal, { useOneSignalSetup } from 'react-onesignal';
import React from 'react';


function OneSignalUtil(callback) {
  useOneSignalSetup(callback);
  return <div></div>;
}
export default OneSignalUtil;
```

**Comment by ducnm2359** [comment]
It would be nice if you have example when setup react-onesignal. 
I still got this error even when I tried many ways from normal to hook.
Thank you

**Comment by witalobenicio** [comment]
For those who may still be having this problem, check if you got the two files that OneSignal provides after you configure your website in their platform.
You need to put them in <project-root>/public/

**Comment by zausailov** [comment]
I have the same issue. Even after adding files that OneSignal provides. My code

`useEffect(() => {
        const options = {
            allowLocalhostAsSecureOrigin:true,
            notifyButton: {
                enable: true,
                size: 'small'
            }
        }

        OneSignal.initialize('appID', options);

        OneSignal.registerForPushNotifications();
    }, []);`

Any ideas how to fix this?

**Comment by Luca8991** [comment]
> Hey there @thearchibold !
> 
> It's possible that OneSignal hasn't initialized yet, so you're getting this error because you're trying to configure it before it was completely initialized.
> 
> Have you tried using our hook to handle OneSignal configuration?
> 
> Here's an example:
> 
> ```js
> import OneSignal, { useOneSignalSetup } from 'react-onesignal';
> 
> type AppProps = {
>   user: {
>     id: string;
>     email: string;
>   };
> };
> 
> function App(props: AppProps) {
>   const { user } = props;
> 
>   useOneSignalSetup(() => {
>     OneSignal.setEmail(user.email);
>     OneSignal.setExternalUserId(user.id);
>   });
> }
> ```

It doesn't work for me. @pedro-lb, can you also upload a complete setup example? I can't really get where to call `OneSignal.initialize()` function. Now I'm calling it in `App.tsx`:
```js
import OneSignal, { useOneSignalSetup } from 'react-onesignal';

OneSignal.initialize('myAppId', {
  allowLocalhostAsSecureOrigin: true,
  notifyButton: {
    enable: false,
  }
});

const App: React.FC = () => {

  useOneSignalSetup(() => {
    // here it doesn't execute
    OneSignal.getNotificationPermission().then(r => console.log(r));
    OneSignal.showSlidedownPrompt();
  });
  // my code continues...
}
```
Can you please help me?

**Comment by DaNiELChIoRo** [comment]
I guest this might be because the hole project is more for the backend side, isn't it? That might be why at the front we cannot get the playerId before declaring it

**Comment by Dakojr** [comment]
In your App.js, call the Onesignal.initialize :

`
import OneSignal from 'react-onesignal';

  const options = {
    allowLocalhostAsSecureOrigin: true,
    notifyButton: {
      enable: false,
    },
    persistNotification: true,
    autoResubscribe: true,
    autoRegister: true,
    safari_web_id: "safari-web-id",
  };

  useEffect(() => {
    OneSignal.initialize("app-id", options);
  }, []);
`
And then in, X.js, here you can call the onesignal-react hook "useOneSignalSetup".

`
import OneSignal, { useOneSignalSetup } from "react-onesignal";

useOneSignalSetup(() => {
  console.log("it's setup");

  const currentPermission = await OneSignal.getNotificationPermission();
});
`

**Comment by rgomezp** [comment]
Please update to the latest release.

Cheers!
