### ISSUE TITLE
Error when i try use bind in callback func

### ISSUE THREAD

**Issue by IagoFreire** [OneSignal/react-onesignal#24]
When i try use 'bind' in callback func the code bellow i received a error 

```
const that = this.handleNotificationInit.bind(this);

        const events = [
            {
                listener: 'once',
                event: 'subscriptionChange',
                callback: that
            }
        ];

        OneSignal.initialize(baseNotificationId, {}, events);
```

"Uncaught SyntaxError: Unexpected identifier
    at injectScript (index.es.js:120)
    at injectModuleScript (index.es.js:137)
    at Object.initialize (index.es.js:155)
    at new App (App.tsx:151)
    at new App (eval at ES6ProxyComponentFactory (react-hot-loader.development.js:NaN), <anonymous>:14:7)
    at constructClassInstance (react-dom.development.js:14204)
    at updateClassComponent (react-dom.development.js:18413)
    at beginWork$1 (react-dom.development.js:20186)
    at beginWork$$1 (react-dom.development.js:25756)
    at performUnitOfWork (react-dom.development.js:24695)" 

When i click in see more, i see this code:

```
 var OneSignal = window.OneSignal || [];
    OneSignal.push(function() {
      OneSignal.once('subscriptionChange', function () { [native code] });
      OneSignal.init({
        appId: "7f8af520-827f-43c2-811a-94727dc20e43",
        
      });
    });
```

**Comment by IagoFreire** [comment]
I managed to solve changing the code below in the lib

```
const buildEventListeners = (eventsArr: IOneSignalEvent[]) => {
    let returnStr = '';

    // Let's make sure we've got an array that isn't empty.
    if (Array.isArray(eventsArr) && eventsArr.length) {
        eventsArr.forEach((event) => {
            event.listener = event.listener || 'on';

            **window[event.listener] = event.callback;**

            returnStr += `OneSignal.${event.listener}('${event.event}', **window.${event.listener}**);`;
        });
    }
    return returnStr;
};
```
I don't know if the is the best solution but work for me

**Comment by pedro-lb** [comment]
Hey there @IagoFreire!

I'm glad you were able to fix the issue locally, but we should patch this in the repo and publish a new version so that the fix is available for all users.

I wasn't able to reproduce the problem locally, can you share a reproducible code? Such as a code sandbox repo, etc.

I'm concerned about this line here:

```ts
window[event.event] = event.callback;
```

We're assigning directly to the `window` object inside a `forEach` loop, so that doesn't seem so right. I would like to test and improve this before publishing a new version.

**Comment by rgomezp** [comment]
Please update to the latest release.

Enjoy!
