### ISSUE TITLE
An example for React JS App Ionic

### ISSUE THREAD

**Issue by dhwalin** [OneSignal/react-onesignal#32]
Hello, I am trying to implement OneSignal using this package in my Ionic App.

I tried my best to implement but some code it gives no popup and some code gives error OneSignal not setup properly. 

In App.tsx I have put following function and run on App load. But it says onesignal is not setup properly.

```
export async function NotificationAlert(){
    

  if(OneSignal.getOneSignalInstance())
    {

        const options = {
            autoResubscribe: true,
    autoRegister: true
        }
    
        OneSignal.initialize('639c84d3-6e70-4a61-9fa3-365fbe795c5a', options);
        OneSignal.registerForPushNotifications();
    }
     

}
```

then in useeffect, I am calling above function. With this code, nothing is happening.

**Comment by rgomezp** [comment]
Howdy,
Can you please try migrating to the 2 version of the package? You can find more info in #44 

Cheers
