### ISSUE TITLE
slidedown prompt and custom link is not supported!

### ISSUE THREAD

**Issue by ashertoufeeq** [OneSignal/react-onesignal#34]

**Comment by pedro-lb** [comment]
Hey there @ashertoufeeq !

Feel free to open a PR implementing this feature, I'll merge and publish it :)

**Comment by rgomezp** [comment]
@ashertoufeeq This is coming soon!

**Comment by sorinraduta** [comment]
Jenant pachet

**Comment by rgomezp** [comment]
Howdy,
These functions are now available in the 2.0 release.

[Please see our 2.0 beta pin for more info](https://github.com/OneSignal/react-onesignal/issues/44)
