### ISSUE TITLE
On the future of `react-onesignal`

### ISSUE THREAD

**Issue by pedro-lb** [OneSignal/react-onesignal#38]
Hi folks! 

I'm creating this issue to make things clear.

As some of you may have noticed, `react-onesignal` has been transferred from my personal account to the [official OneSignal organization](https://github.com/OneSignal).

This means that this package is now the official implementation of OneSignal for React and we're expecting great things to come, such as a better maintenance cycle, more contributors, and better quality.

The development cycle stays the same, and existing pull requests will be reviewed and published as needed.

For more information and/or suggestions, it's a great idea to [create an issue](https://github.com/OneSignal/react-onesignal/issues/new) or contact [me ](https://github.com/pedro-lb) or [Rodrigo](https://github.com/rgomezp).

Cheers! 🥂

**Comment by BigsonLvrocha** [comment]
Congratulations!

**Comment by pedro-lb** [comment]
https://github.com/OneSignal/react-onesignal/issues/44
