### ISSUE TITLE
Adds Ability To use SERVICE_WORKER_PARAM

### ISSUE THREAD

**Issue by andredealmei** [OneSignal/react-onesignal#39]
Ability To use SERVICE_WORKER_PARAM,SERVICE_WORKER_PATH && SERVICE_WORKER_UPDATER_PATH;

documented here https://documentation.onesignal.com/docs/onesignal-service-worker-faq

**Comment by rgomezp** [comment]
Howdy,
Thanks for your patience. This has now been fixed. You are now able to use the initialization parameters:

```js
serviceWorkerParam: { scope: '/assets/' }
```

Read more details [here](https://github.com/OneSignal/OneSignal-Website-SDK/releases/tag/151508).

Enjoy!
