### ISSUE TITLE
Add isPushNotificationsSupported API

### ISSUE THREAD

**Issue by slamacchia** [OneSignal/react-onesignal#51]
Glad to hear OneSignal supporting this package!

Is it possible to add back the `isPushNotificationsSupported()` APi?:
- https://documentation.onesignal.com/docs/web-push-sdk#ispushnotificationssupported-method

Or is there another way of determining this now?

I find this feature useful for hiding web push notification settings in my web app on unsupported browsers (i.e. iOS Safari).

**Comment by nynevi** [comment]
I would also like this to be officially supported but just fyi `window.OneSignal.isPushNotificationsSupported()` works already though. not sure if there is a downside on using it.

**Comment by rgomezp** [comment]
Howdy,
There is no downside to using it @nynevi

**Comment by rgomezp** [comment]
Closing since we have decided not to add to the existing API & there is a workaround (mentioned above).

In the upcoming major release, this will be included!

Enjoy!
