### ISSUE TITLE
logoutEmail() should probably return a promise

### ISSUE THREAD

**Issue by statico** [OneSignal/react-onesignal#53]
Right now it returns `void`, but clearly there's a network request happening. Chrome is showing me an uncaught exception when there's an error with the call. It would be nice to be able to catch this in my own code.

![CleanShot 2021-11-09 at 13 56 22](https://user-images.githubusercontent.com/137158/141011330-39cfefb4-f63c-4e8e-9a79-0270633b1f90.png)

**Comment by rgomezp** [comment]
Howdy,
Thanks for reporting. You are right, this should return a promise. 

Thanks for your patience while we resolve.
