### ISSUE TITLE
[question]: How can I invoke the sendSelfNotification method in a React Setup?

### ISSUE THREAD

**Issue by nisar-snsw** [OneSignal/react-onesignal#76]
### How can we help?

**Issue:**
Is there a way that I can invoke the sendSelfNotification method in a React Setup?

**Error:**
I get this error when that method is invoked:
Uncaught (in promise) TypeError: Vi.a.sendSelfNotification is not a function

Code snippet for testing _sendSelfNotification_ method:
```
import OneSignal from 'react-onesignal';

const onOpen = async () => {
    const isPushEnabled = await OneSignal.isPushNotificationsEnabled();
    if (!isPushEnabled) {
      await OneSignal.registerForPushNotifications();
    } else {
      OneSignal.sendSelfNotification();
}
```

**Comment by rgomezp** [comment]
Howdy,
This function is not yet supported. I will mark it as a feature request.

In the meantime, you can still use the OneSignal window object to invoke it:
`window.OneSignal.sendSelfNotification()`

Thanks for your patience.

**Comment by rgomezp** [comment]
Howdy,
We have decided to not add this to the API as we are preparing to release the brand new major release with a totally new api. In the meantime, you can use the workaround mentioned previously.
