### ISSUE TITLE
[question]: How can I hide the bell?

### ISSUE THREAD

**Issue by agustinramos** [OneSignal/react-onesignal#92]
### How can we help?

Hii, nice to meet you guys,

Just I wanna now how can I hide the bell with this library.

Thanks!

**Comment by rgomezp** [comment]
Howdy,
Make sure you have your app configured to "Custom Code" in your dashboard. 

The bell is configured in Custom Code setups via [init options](https://documentation.onesignal.com/docs/web-push-sdk#init-notifybutton-parameters).

Enjoy!

**Comment by agustinramos** [comment]
window.OneSignal.notifyButton.launcher.hide() ...

thanks!!
